Meditor/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',views.index),
    path('/editSavedScript/<int:id>', views.edit_Script),
    path('/editTranslatedScript/<int:id>', views.edit_TScript),
    path('/<int:id>', views.delete_script)
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project3/urls.py
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views #import this
from django.contrib.auth.views import LogoutView
from users import views as user_view
from django.contrib.auth import views as auth
from payment.views import payment_success
urlpatterns=[
path('scripteditor',include('Meditor.urls')),
path('', include('mnfapp.urls')),
path('narration/', include('narration.urls')),
path('conversion/', include('conversion.urls')),
path('users/', include('users.urls')),
path('videos/', include('videos.urls')),
path('pay/', include('payment.urls')),
path('paytest/', include('testpay.urls')),
path('audit/', include('scriptAudit.urls')),

path('events/', include('events.urls')),
path('success/',payment_success,name="payment-success"),
path('admin/', admin.site.urls),
path('accounts/', include('allauth.urls')), 
path('myauth', TemplateView.as_view(template_name="users/fbLogin.html")),

path('logout', LogoutView.as_view()),
path('register/', user_view.register, name='register'),
path('activate/<uidb64>/<token>', user_view.activate, name='activate'),
path('social-auth/', include('social_django.urls', namespace="social")),
path('accounts/', include('allauth.urls')),
path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'), 
path("password_reset", auth_views.PasswordResetView.as_view(template_name = 'password/password_reset.html'), name="password_reset"),
path('verification/', include('verify_email.urls')),

path('register/', user_view.register, name ='register'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('password-reset/', views.password_reset, name='password_reset'),
    path('password-reset/done', views.password_reset_done,
         name='password_reset_done'),
    path('login/', views.auth_login, name='auth_login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('profile/',views.imgUpload, name='userprofile')
]

Meditor/models.py
from django.db import models
from tinymce.models import HTMLField
from django.contrib.auth.models import User

class editor(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    ScriptName = models.CharField(max_length=50, blank=  True, null= True)
    bodyTxt = HTMLField(blank=  True, null= True)


class ConversionEditor(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    ScriptName = models.CharField(max_length=50, blank=  True, null= True)
    bodyTxt = HTMLField(blank=  True, null= True)



class ScriptToEdit(models.Model):
    script = models.FileField(upload_to="script_Editor/userScripts")
    dateCreated = models.DateField(auto_now_add = True)
    class Meta:
        db_table = "Scripts"



class FeedBack(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add = True)
    FormId = models.AutoField(primary_key=True)
    RateValue = models.CharField(max_length=50)
    Name = models.CharField(max_length=30)
    Email = models.CharField(max_length=50)
    Description = models.CharField(max_length=500)
    RateNarration = models.CharField(default="", max_length=20)
    RateConversion = models.CharField(default="", max_length=20)
    

Meditor/forms.py
from django import forms
from .models import editor, FeedBack, ConversionEditor
from tinymce.models import HTMLField
from tinymce.widgets import TinyMCE
class ScriptEditor(forms.ModelForm):
    ScriptName = forms.CharField(max_length=50)
    bodyTxt = forms.CharField(widget=TinyMCE(attrs={'cols': 30, 'rows': 30 ,'style': 'text-align:right;'}))
    class Meta:
        model = editor
        fields = ["ScriptName","bodyTxt"]


class CScriptEditor(forms.ModelForm):
    ScriptName = forms.CharField(max_length=50)
    bodyTxt = forms.CharField(widget=TinyMCE(attrs={'cols': 30, 'rows': 30 ,'style': 'text-align:right;'}))
    class Meta:
        model = ConversionEditor
        fields = ["ScriptName","bodyTxt"]




class ScriptEdit(forms.Form):
   script = forms.FileField()

class InputText(forms.Form):
    mySavedName = forms.CharField(max_length=50)
    AreaTxt = forms.CharField(widget=forms.Textarea)

Meditor/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import re
from docx2pdf import convert 
from .upload import scriptUpload
from langdetect import detect
from .forms import ScriptEdit, InputText,ScriptEditor,CScriptEditor
from .models import ScriptToEdit, ConversionEditor,editor
from mnfapp.models import MNFScriptDatabase

# for Users


from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


def save_dict():
    document = Document('F:/MNF/translations/final.docx')
    table = document.tables[0]
    data = []
    keys = None
    for i, row in enumerate(table.rows):
        text = (cell.text for cell in row.cells)
        
        if i == 0:
            keys = tuple(text)
            continue
        row_data = dict(zip(keys, text))
        data.append(row_data)
    df = pd.DataFrame(data)
    myDict = dict(zip(df.Input,df.Output1))
    return myDict

# Create your views here.
login_required(login_url = 'login')
def index(request):
    ProgressRecorder = ProgressRecorder()
    saved = False
    form = ScriptEditor(request.POST)
    MyScript = ScriptEdit()
    text = editor()
    MyURL = ""
    stra = ""
    message = ""
    filename = ""
    form3 = InputText()
    webp_list= ScriptToEdit.objects.all()
    TS_list = MNFScriptDatabase.objects.filter(user_id = request.user)
    webpp_list= editor.objects.filter(user = request.user)

    if request.method == "POST":
        #Get the posted form
        MyScript = ScriptEdit(request.POST, request.FILES)
        form = ScriptEditor(request.POST)
        if form3.is_valid():
            form3 = InputText()
            stra=form3.GET["AreaTxt"]
        if MyScript.is_valid():
            Script = ScriptToEdit()
            Script.script = MyScript.cleaned_data.get("script")
            
            if Script.script in webp_list:
                message= "File Already Exist"
            else:
                Script.save()
                saved = True
            MyURL = Script.script.url
            filename = Script.script.name
            
            if MyURL[-4:] == "docx":
                try:
                    convert("F:/MNF/project3"+MyURL, "F:/MNF/project3"+MyURL[:-4]+"pdf")
                    print("doc file uploaded")
                    stra = scriptUpload(MyURL[:-4]+"pdf")
                    print(detect(stra))
                    
                except:
                    print("some error occured")
            
            if MyURL[-3:] == "pdf":
                stra = scriptUpload(MyURL)
                print(detect(stra))
                
            form = ScriptEditor()
            
        if form.is_valid():
            text=editor(user = request.user)
            text.ScriptName = form.cleaned_data.get("ScriptName")
            text.bodyTxt=form.cleaned_data.get("bodyTxt")
            text.save()
            return HttpResponseRedirect("/scripteditor")
            
    else:
        pass
    return render(request, 'editScript.html',{'filename':filename, "form":form,'TS_list':TS_list, "form2": MyScript,"stra":stra,'web_list':webp_list,'webpp_list':webpp_list, "message":message,"form3":form3})


login_required(login_url = 'login')
def edit_Script(request, id):
    """Edit an existing post."""

    webp_list= editor.objects.filter(user= request.user)
    webpp_list= editor.objects.filter(user = request.user)
    post = editor.objects.get(id=id, user = request.user)
    st = id
    editorData = editor()
    #print(parseDict)
    editor.objects.get(id=st).delete()
    if request != 'POST':
        form = ScriptEditor(instance=post)

    else:
        form = ScriptEditor(instance=post,user = request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/scripteditor")

    context = {'post': post, 'form': form,'web_list':webp_list,'webpp_list':webpp_list,}
    return render(request, 'index2.html', context)


def edit_TScript(request, id):
    stra =""
    data = MNFScriptDatabase.objects.filter(id = id)
    form = CScriptEditor(request.POST)
    for i in data:
        script_title = i.script_title
        edited = ConversionEditor.objects.filter(ScriptName = script_title)
    if edited:
        for j in edited:
            stra = j.bodyTxt
            ConversionEditor.objects.get(ScriptName = i.script_title).delete()
            ln = False
            print("data from editor")
    else:
        MyURL = i.translated_script_path
        stra = scriptUpload(MyURL)
        ln = True
        print("data from conversion")
    if request.method == 'POST':
        if form.is_valid():
            text=ConversionEditor(user = request.user)
            text.ScriptName = form.cleaned_data.get("ScriptName")
            text.bodyTxt=form.cleaned_data.get("bodyTxt")
            text.save()
            return HttpResponseRedirect("/scripteditor")
        else:
            print("problem arrived")   

    return render(request, 'index3.html',{'form':form, 'stra':stra,'ln' : ln, 'script_title': script_title})


def delete_script(request, id):
    editor.objects.get(id = id).delete()
    return HttpResponseRedirect("/scripteditor")

Meditor/templates/data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        .container{    
            padding: 1em;
            margin: 1em;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }
        .content{
            display: grid;
            grid-template-columns: auto auto auto auto auto;
        }
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>feedback Form Data</title>
</head>
<body>
    <h2 style="text-align: center;">My Edited Scripts</h2>
                {% if webpp_list %}
                {% for us in webpp_list %}                
                <div class="content">
                        <div class="{{us.Name}}"><strong>Name: {{us.Name}} <br>Rating: {{us.RateValue}}/5 <br> Description: {{us.Description}} </strong></div>
                                
                    {% endfor %}
                </div>
                {% else %}
                  <p style="color: red;font-size: 1.2em;">No Data is available</p>
                {% endif %}
            
            </div>
</body>
</html>

Meditor/templates/feedback3.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'file.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MNF Feedback Form</title>
</head>
<body>
    <div class="container">
        <h1>Feedback Form</h1>
        <div class="star-widget">
            <input type="radio" onclick="func('5-rating', 'Excellent')" name="rate" id="rate-5">
            <label for="rate-5" class="fas fa-star"></label>
            <input type="radio" onclick="func('4-rating', 'Very Good')" name="rate" id="rate-4">
            <label for="rate-4" class="fas fa-star"></label>
            <input type="radio" onclick="func('3-rating', 'Good')" name="rate" id="rate-3">
            <label for="rate-3" class="fas fa-star"></label>
            <input type="radio" onclick="func('2-rating', 'poor')" name="rate" id="rate-2">
            <label for="rate-2" class="fas fa-star"></label>
            <input type="radio" onclick="func('1-rating', 'very-poor')" name="rate" id="rate-1">
            <label for="rate-1" class="fas fa-star"></label> 
        </div>
        <h2 id="descValue"></h2>
        <form id="other-area" enctype = "multipart/form-data" method="POST" name="form">
            {% csrf_token %}
            <input type="text" style="display: none;" name="RateValue" id="id_RateValue" required>
            <input type="text" class="" id="" placeholder="Your Name" name = "Name" required/> <br>
            <div id= "services-used">
                <span>Service Used</span>
                <a onclick="openMyService()" id="plus-button"><b class="fa fa-plus"></b></a>
            </div>
            <div id="MyServices">
                <div id="rateNarration">
                    <span>Rate Narration</span>
                    <select id="Rate-Narration" name="RateNarration" required>
                        <option value="">Rate</option>
                        <option value="5-rating" name="RateNarration">Excellent</option>
                        <option value="4-rating" name="RateNarration">Very Good</option>
                        <option value="3-rating" name="RateNarration">Good</option>
                        <option value="2-rating" name="RateNarration">Average</option>
                        <option value="1-rating" name="RateNarration">Poor</option>
                      </select>
                </div>
                <div id="rateConversion">
                    <span>Rate Conversion</span>
                    <select id="Rate-Conversion" name="RateConversion" required>
                        <option value="">Rate</option>
                        <option value="5-rating" name="RateConversion">Excellent</option>
                        <option value="4-rating" name="RateConversion">Very Good</option>
                        <option value="3-rating" name="RateConversion">Good</option>
                        <option value="2-rating" name="RateConversion">Average</option>
                        <option value="1-rating" name="RateConversion">Poor</option>
                    </select>
                </div>
            </div>
            
            <input type="text" class="" id="" placeholder="XYZ@email.com" name = "Email" required/> <br>
            <textarea name="Description" id="" cols="60" rows="10" placeholder=" Say Somthing..." required></textarea><br>
            <button id="submit" type="submit">Submit</button>
        </form>
        
    </div>
</body>
<script>
    function openMyService(){
        if(document.getElementById('MyServices').style.display == 'none'){
            document.getElementById('MyServices').style.display = 'block';
            document.getElementById("plus-button").innerHTML = '<b class="fa fa-minus"></b>';
        }else{
            document.getElementById('MyServices').style.display = 'none'         
            document.getElementById("plus-button").innerHTML = '<b class="fa fa-plus"></b>'
        }
        
    }
    
    document.getElementById('id_RateValue').style.display='none';
    function func(rateValue, desc){
        var tagValue = document.getElementById('descValue').innerText = desc;
        var Value = document.getElementById('id_RateValue').value = rateValue;
        document.getElementById('other-area').style.display ='block';

    }
    
</script>
</html>

Meditor/templates/file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form name = "form" enctype = "multipart/form-data" action = "/" method = "POST" >
        {% csrf_token %}
          <input type = "file" style = "margin-left:20%;" placeholder = "Picture" name = "picture" />
          <button  type = "submit" value = "Import" ></button>
    </form>
</body>
</html>

Meditor/templates/index2.html
{% extends 'mnfapp/base.html' %}
{% load static %}
{% block title %}
ScriptEeditor  
{% endblock %}





{% block content %}

<!--  CSS  -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static '/script.js' %}" type="text/javascript"></script> 
<link rel="stylesheet" href="{% static 'main.css'%}">
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="{%static 'plugin/tinymce/tinymce.min.js'%}"></script>
<script src="{%static 'plugin/tinymce/init-tinymce.js'%}" ></script>


<!--HTML-->


<div class="grid-container">
  <div class="Scripts-list">
      <div class="myblog-container">
          <h2>My Edited Scripts</h2>
          {% if webpp_list %}
            {% for us in webpp_list %}
                  <div class="content">
                          <a href="{{us.id}}" type="submit">{{us.ScriptName}}</a>
                  </div>
            {% endfor %}
      
          {% else %}
            <p style="color: red;font-size: 1.2em;">No Data is available</p>
          {% endif %}
      
      </div>
  </div>
  <div class="Script-editor">
      <h2>Script Editor</h2>
      <form class="form" name="form2" enctype = "multipart/form-data" action = "/scripteditor" method = "POST">
          {% csrf_token %}
          {{form}}
          <button  type = "submit" value = "save" >save</button>
      </form>
  </div>        
</div>


<!--JAVASCRIPT-->


<script>
  var myfile="";
  $('#MyScript').on( 'change', function() {
     myfile= $( this ).val();
     var ext = myfile.split('.').pop();
     if(ext=="pdf"){
     } else{
         alert("only PDF files allowed");
         location.reload()
     }
  });

 
  </script>
<script>


</script>

{% endblock %}